# Generated by Django 5.0.6 on 2024-06-23 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=5, null=True)),
                ('question', models.TextField(blank=True, max_length=500, null=True)),
                ('aAnswer', models.CharField(blank=True, max_length=350, null=True)),
                ('bAnswer', models.CharField(blank=True, max_length=350, null=True)),
                ('cAnswer', models.CharField(blank=True, max_length=350, null=True)),
                ('dAnswer', models.CharField(blank=True, max_length=350, null=True)),
                ('correctAnswer', models.CharField(blank=True, max_length=5, null=True)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.category')),
            ],
        ),
    ]
