# Generated by Django 5.0.6 on 2024-06-23 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.category'),
        ),
        migrations.AlterField(
            model_name='test',
            name='number',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
