# Generated by Django 5.0.6 on 2024-06-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_test_category_alter_test_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
