# Generated by Django 5.0.6 on 2024-06-30 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_mylearning'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylearning',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
