# Generated by Django 5.0.6 on 2024-06-30 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_mylearning_datetime_alter_useranswer_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylearning',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.category'),
        ),
    ]
