# Generated by Django 5.0.6 on 2024-06-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_test_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='correctAnswer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('No detallado', 'No detallado')], max_length=15, null=True),
        ),
    ]
