# Generated by Django 5.0.6 on 2024-06-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='test',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
